[project]
name = "ComfyUI"
version = "0.3.46"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"

[project.urls]
homepage = "https://www.comfy.org/"
repository = "https://github.com/comfyanonymous/ComfyUI"
documentation = "https://docs.comfy.org/"

[tool.ruff]
lint.select = [
  "E",    # pycodestyle errors
  "I",    # isort
  "N805", # invalid-first-argument-name-for-method
  "S307", # suspicious-eval-usage
  "S102", # exec
  "T",    # print-usage
  "W",
  # The "F" series in Ruff stands for "Pyflakes" rules, which catch various Python syntax errors and undefined names.
  # See all rules here: https://docs.astral.sh/ruff/rules/#pyflakes-f
  "F",
]
lint.ignore = ["E501"]  # disable line-length checking
exclude = ["*.ipynb", "**/generated/*.pyi"]

[tool.ruff.lint.per-file-ignores]
"!comfy_extras/v3/*" = ["E", "I"]  # enable these rules only for V3 nodes
